name: Contributor License Agreement
description: Sign the Contributor License Agreement
title: "[CLA]: "
labels: [CLA]
body:
- type: markdown
  attributes:
    value: |
      Thank you for your submission, we really appreciate it.
- type: checkboxes
  attributes:
    label: Signature
    description: Like many open-source projects, we ask that you to sign our Contributor License Agreement before we can accept your contribution.
    options:
    - label: I have read the CLA Document and I hereby sign the CLA
      required: true
