name: Contributor License Agreement (test)
description: Sign the Contributor License Agreement
title: "[CLA]: "
labels: [CLA]
body:
- type: checkboxes
  id: signature
  attributes:
    label: Signature
    description: Like many open-source projects, we ask that you to sign our Contributor License Agreement before we can accept your contribution.
    options:
    - label: I have read the CLA Document and I hereby sign the CLA
      required: true
      
