type: contributor-assistant/settings
version: 1
data:
  - type: contributor-assistant/signatures/settings
    version: 1
    data:
      storage:
        form: signature-form.yml
      ignoreList: ["@CONTRIBUTOR"]
